### ISSUE TITLE
 Add Navbar to Main Page

### ISSUE THREAD

**Issue by deepak-raaaz** [deepak-raaaz/web-dev-projects#6]
Implement a responsive and user-friendly navigation bar on the main page. The navbar should include links to different project sections and ensure easy navigation for users.

**Comment by Snehalgupta-07** [comment]
Hi @deepak-raaaz i can do this task can pls assign it to me

**Comment by sairiteshdomakuntla** [comment]
heyy @deepak-raaaz , i think i can do this, can you assign this to me?

**Comment by deepak-raaaz** [comment]
@sairiteshdomakuntla Assigned! If you appreciate the work, don't forget to leave us a star ⭐

**Comment by JollyJolli** [comment]
Hey there! I just made a sketch

![image](https://github.com/user-attachments/assets/d2e0db69-a81a-41ba-a8b5-54b85dbc5395)

**Comment by BaniSinghgithub** [comment]
hello sir @deepak-raaaz , can you assign this work to me please.

**Comment by Snehalgupta-07** [comment]
> hello sir @deepak-raaaz , can you assign this work to me please. 

I am working on it

**Comment by BaniSinghgithub** [comment]
but more than one person can be assigned

**Comment by deepak-raaaz** [comment]
hey @BaniSinghgithub the navbar is added, but it’s not responsive. You can work on making it responsive and feel free to change the UI as well. Thanks!
