### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by deepak-raaaz** [deepak-raaaz/web-dev-projects#7]
Create a footer for the main page that contains important links such as "About Us," "Contact," "Privacy Policy," and social media icons. This will enhance user experience and provide easy access to additional information.

**Comment by Snehalgupta-07** [comment]
Hi @deepak-raaaz, i can do this task can u pls assign it to me :)

**Comment by sairiteshdomakuntla** [comment]
hello @deepak-raaaz , can you assign this to me?

**Comment by deepak-raaaz** [comment]
@Snehalgupta-07 Task assigned. If you find it helpful, we’d love your support with a star ⭐!

**Comment by himasnhu018** [comment]
hi can you please assign me that issue.

**Comment by BaniSinghgithub** [comment]
hello sir @deepak-raaaz , can you pls assign this task to me

**Comment by deepak-raaaz** [comment]
@himasnhu018 Sure, you can work on this issue!

**Comment by himasnhu018** [comment]
I created the pull request can you please review the changes and accept my pull request. and add the label kindly.
