### ISSUE TITLE
Add a Detailed README.md File for Quote Generator Project 

### ISSUE THREAD

**Issue by deepak-raaaz** [deepak-raaaz/web-dev-projects#8]
Issue: Create a detailed README.md file for the Quote Generator project

We need to create a comprehensive README.md file for the Quote Generator project. This file should provide essential details about the project, making it user-friendly and informative. The README.md should include the following sections:

    Project Name: Clearly state the name of the project.
    Description: Provide a brief overview of the project and its purpose.
    Features: List the key functionalities that the application offers.
    Built With: Specify the technologies and tools used in the development of the project.
    Live Demo: Include a link to the live version of the application.
    How to Use: Offer step-by-step instructions for users to navigate and utilize the application.

Each section in the README.md is crucial for informing and guiding users or developers interacting with the project. It ensures they understand the project's purpose, features, and how to use the app effortlessly.

**Comment by AqibAliMughal** [comment]
Hi, I have reviewed your application on my system & I can write a user-friendly readme. However, the quote generator API is not fetching the data, and it seems like their server is down.

**Comment by deepak-raaaz** [comment]
@AqibAliMughal Hey, I’ve assigned you to this task. You can also take on more issues to help us out!
